name: Test
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  android-compile:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v3
      with:
        node-version: '16.x'
        cache: 'yarn'
        cache-dependency-path: '**/yarn.lock'

    - uses: actions/cache@v2
      with:
        path: |
          ~/.npm
          ~/node_modules
          ~/ci/node_modules
          ~/.config/yarn/global
        key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install Yarn
      run: |
        npm install -g yarn

    - name: Yarn
      run: |
        yarn install
        cd ci
        yarn

    - name: Compile Android (Debug)
      working-directory: ./ci/android/
      run: ./gradlew assembleDebug

  ios-compile:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v3
      with:
        node-version: '16.x'
        cache: 'yarn'
        cache-dependency-path: '**/yarn.lock'

    - uses: actions/cache@v2
      with:
        path: |
          ~/.npm
          ~/node_modules
          ~/ci/node_modules
          ~/.config/yarn/global
        key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Cache cocoapods
      uses: actions/cache@v2
      with:
        path: ./ci/ios/Pods
        key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-pods-

    - name: Install Yarn
      run: |
        npm install -g yarn
        yarn

    - name: Yarn
      run: |
        yarn install
        cd ci/
        yarn
        cd ios/
        pod install

    - name: Compile iOS
      working-directory: ./ci/ios/
      run: |
        set -o pipefail && \
        xcodebuild -workspace LivekitReactNativeExample.xcworkspace/ \
          -scheme LivekitReactNativeExample \
          -destination generic/platform=iOS \
          -configuration Debug \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGN_ENTITLEMENTS="" \
          CODE_SIGNING_ALLOWED="NO" \
          clean build | xcpretty