name: Test
on:
  push:
    branches: [main]
    paths-ignore:
      - '**.md'
  pull_request:
    branches: [main]
    paths-ignore:
      - '**.md'

jobs:
  android-compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'

      - uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: 'yarn'
          cache-dependency-path: '**/yarn.lock'

      - uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            ~/node_modules
            ~/ci/node_modules
            ~/.config/yarn/global
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Yarn
        run: |
          npm install -g yarn

      - name: Yarn
        run: |
          yarn install
          cd ci
          yarn

      - name: Compile Android (Debug)
        working-directory: ./ci/android/
        run: ./gradlew assembleDebug

  ios-compile:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: 'yarn'
          cache-dependency-path: '**/yarn.lock'

      - uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            ~/node_modules
            ~/ci/node_modules
            ~/.config/yarn/global
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Cache gem bundle
        uses: actions/cache@v4
        with:
          path: ./ci/vendor
          key: ${{ runner.os }}-gembundle-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gembundle-

      - name: Cache cocoapods
        uses: actions/cache@v4
        with:
          path: ./ci/ios/Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-

      - name: Install Yarn
        run: |
          npm install -g yarn
          yarn

      - name: Yarn
        run: |
          yarn install
          cd ci/
          yarn
      - name: Pods
        run: |
          cd ci/ios/
          bundle install
          bundle exec pod update hermes-engine --no-repo-update
          bundle exec pod install --verbose

      - name: Compile iOS
        working-directory: ./ci/ios/
        run: |
          set -o pipefail && \
          xcodebuild -workspace ci.xcworkspace/ \
            -scheme ci \
            -destination generic/platform=iOS \
            -configuration Debug \
            -verbose \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGN_ENTITLEMENTS="" \
            CODE_SIGNING_ALLOWED="NO" \
            clean build | xcpretty
